### ISSUE TITLE
AWS tooling

### ISSUE THREAD

**Issue by otrosien** [ePages-de/mac-dev-setup#10]
For AWS command-line tools I would like to add python3 and aws-cli. Ok or should I use my own branch for that?

**Comment by otrosien** [comment]
@jensfischerhh ?

**Comment by jensfischer1515** [comment]
I would like to use different Ansible roles for grouping related tools, so that it is easy to specify what to include for one's setup. Until we have this in place I would rather limit the tools to what we use in our daily work. Python3 might be a generic addition, but currently I don't see AWS on our roadmap.

**Comment by otrosien** [comment]
no prob. For now I'll just add it to my fork.
