### ISSUE TITLE
Add git autocompletion

### ISSUE THREAD

**Issue by jmewes** [ePages-de/mac-dev-setup#15]
After the setup I had to install the git autocompletion manually. I think we should automate this as well.

See https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks#Auto-Completion

**Comment by jensfischer1515** [comment]
I don't think there is anything to do here, since it should work already. See https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion#os-x--macos and https://github.com/ePages-de/mac-dev-setup/blob/master/common/templates/.bash_profile.j2#L8-L10

Maybe you did not open a new shell so that changes to `~/.bash_profile` were taken into account?
